apiVersion: v1
data:
  API_PORT: "8080"
  API_DB_FILEPATH: /var/lib/synergychat/api/db.json
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"API_PORT":"8080"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"synergychat-api-configmap","namespace":"default"}}
  creationTimestamp: "2025-12-20T09:28:09Z"
  name: synergychat-api-configmap
  namespace: default
  resourceVersion: "1095567"
  uid: b358f572-f272-4d62-9f6b-bd94f0c6a709
