apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"synergychat-crawler"},"name":"synergychat-crawler","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"synergychat-crawler"}},"template":{"metadata":{"labels":{"app":"synergychat-crawler"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"synergychat-crawler-configmap"}}],"image":"bootdotdev/synergychat-crawler:latest","name":"synergychat-crawler"}]}}}}
  creationTimestamp: "2025-12-20T09:59:50Z"
  generation: 1
  labels:
    app: synergychat-crawler
  name: synergychat-crawler
  namespace: default
  resourceVersion: "1097158"
  uid: 6d879a34-a3e5-4a01-8ca4-88fbaae01693
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-crawler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
